"use client";

import Link from "next/link";
import { ArrowLeft, FileText, Mail, Shield } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-neutral-50 dark:bg-neutral-950">
            {/* Header */}
            <header className="sticky top-0 z-10 bg-neutral-50/80 dark:bg-neutral-950/80 backdrop-blur-md border-b border-neutral-200 dark:border-white/10">
                <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-4">
                    <Link
                        href="/"
                        className="flex items-center gap-2 text-sm text-neutral-600 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        Back to Home
                    </Link>
                </div>
            </header>

            <main className="max-w-4xl mx-auto px-6 py-16">
                <div className="flex items-center gap-4 mb-8">
                    <div className="w-14 h-14 rounded-2xl bg-blue-100 dark:bg-blue-500/20 flex items-center justify-center">
                        <FileText className="w-7 h-7 text-blue-600 dark:text-blue-400" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-bold text-neutral-900 dark:text-white">Terms of Service</h1>
                        <p className="text-neutral-500 dark:text-neutral-400">Last updated: January 2025</p>
                    </div>
                </div>

                <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
                    <div className="p-6 bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 rounded-xl">
                        <div className="flex items-start gap-3">
                            <Shield className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5" />
                            <div>
                                <h3 className="font-bold text-amber-800 dark:text-amber-300 m-0 mb-2">Important Notice About AI-Generated Content</h3>
                                <p className="text-amber-700 dark:text-amber-400 text-sm m-0">
                                    All educational content on Gakuen is generated by artificial intelligence. AI-generated content is not protected by copyright.
                                    If you believe any content resembles your copyrighted work, please <Link href="/contact" className="underline font-medium">contact us</Link> immediately
                                    and we will review and remove it if necessary.
                                </p>
                            </div>
                        </div>
                    </div>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">1. Acceptance of Terms</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            By accessing or using Gakuen (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
                            If you do not agree to these terms, you may not access or use the Service. These terms constitute
                            a legally binding agreement between you and Gakuen.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">2. Description of Service</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            Gakuen provides an AI-powered educational platform including but not limited to: AI tutoring services,
                            course materials, progress tracking, and personalized learning experiences. The Service is provided
                            &quot;as is&quot; and we reserve the right to modify, suspend, or discontinue any part of the Service at any time.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">3. AI-Generated Content</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            <strong>All content on this platform is generated by artificial intelligence.</strong> This includes but is not limited to:
                        </p>
                        <ul className="text-neutral-600 dark:text-neutral-300 list-disc pl-6 space-y-2">
                            <li>Course materials and lessons</li>
                            <li>Explanations and tutoring responses</li>
                            <li>Practice problems and assessments</li>
                            <li>Recommendations and suggestions</li>
                        </ul>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            AI-generated content may contain errors or inaccuracies. You should verify important information
                            from authoritative sources. We are not liable for decisions made based on AI-generated content.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">4. Copyright & Intellectual Property</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            Under current law, AI-generated content is generally not eligible for copyright protection.
                            The AI-generated educational materials provided through this Service are offered for your personal
                            educational use. If you believe any content on our platform infringes your copyright or intellectual
                            property rights, please contact us immediately at <Link href="/contact" className="text-blue-600 dark:text-blue-400 hover:underline">our contact page</Link>.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">5. User Accounts</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            You are responsible for maintaining the confidentiality of your account credentials and for all
                            activities that occur under your account. You must provide accurate, current, and complete
                            information during registration. You may not share your account with others or allow unauthorized access.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">6. Privacy & Data Collection</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            We collect and process personal data as described in our <Link href="/privacy" className="text-blue-600 dark:text-blue-400 hover:underline">Privacy Policy</Link>.
                            By using the Service, you consent to:
                        </p>
                        <ul className="text-neutral-600 dark:text-neutral-300 list-disc pl-6 space-y-2">
                            <li>Collection of usage data, learning progress, and interaction patterns</li>
                            <li>Processing of data by AI systems for personalization</li>
                            <li>Storage of data on secure cloud servers</li>
                            <li>Use of anonymized data for service improvement</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">7. Payment & Refunds</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            Paid features are billed in advance on a subscription basis. Refunds are provided in accordance
                            with applicable law. We reserve the right to change pricing with 30 days notice. Continued use
                            after price changes constitutes acceptance.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">8. Limitation of Liability</h2>
                        <p className="text-neutral-600 dark:text-neutral-300 uppercase text-sm">
                            TO THE MAXIMUM EXTENT PERMITTED BY LAW, GAKUEN SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
                            SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA,
                            OR GOODWILL. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU IN THE PAST 12 MONTHS.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">9. Indemnification</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            You agree to indemnify and hold harmless Gakuen and its officers, directors, employees, and agents
                            from any claims, damages, losses, or expenses arising from your use of the Service or violation of these Terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">10. Governing Law</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction
                            in which Gakuen operates, without regard to conflict of law principles. Any disputes shall be
                            resolved through binding arbitration.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">11. Changes to Terms</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            We reserve the right to modify these Terms at any time. We will notify users of material changes
                            via email or through the Service. Continued use after changes constitute acceptance of the new Terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-neutral-900 dark:text-white">12. Contact</h2>
                        <p className="text-neutral-600 dark:text-neutral-300">
                            For questions about these Terms, please visit our <Link href="/contact" className="text-blue-600 dark:text-blue-400 hover:underline">Contact Page</Link> or
                            email us at <a href="mailto:legal@gakuen.edu" className="text-blue-600 dark:text-blue-400 hover:underline">legal@gakuen.edu</a>.
                        </p>
                    </section>
                </div>
            </main>
        </div>
    );
}
